cmsku/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls', namespace='members')),
    path('article/', include('articles.urls', namespace='articles'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

members/urls.py
from django.urls import path

from members.views import (
    sign_up_page,
    sign_in_page,
    sign_out_page,
    profile_page,
    deactivate_page,
)

app_name = 'members'

urlpatterns = [
    path('sign-out/', sign_out_page, name='sign-out'),
    path('sign-up/', sign_up_page, name='sign-up'),
    path('profile/', profile_page, name='profile'),
    path('deactivate/', deactivate_page, name='deactivate'),
    path('', sign_in_page, name='sign-in'),
]

members/models.py
import os
import shutil

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

from helpers.models import BaseModel


def photo_path(instance, filename):
    return os.path.join('prof_pic', instance.user.username, filename)


class Member(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to=photo_path)

    def __str__(self):
        return self.user.username


@receiver(post_delete, sender=Member)
def signal_remove_photo(sender, **kwargs):
    member = kwargs.get('instance')
    user_profile_dir = os.path.dirname(member.photo.file.name)

    try:
        shutil.rmtree(user_profile_dir)
    except IOError:
        pass

members/forms.py
from django import forms


class SignUpForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    photo = forms.ImageField()


class SignInForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

members/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse

from members.forms import SignUpForm, SignInForm
from members.models import Member


def sign_up_page(request):
    # FBV: function based views
    form = SignUpForm(request.POST or None, request.FILES or None, use_required_attribute=False)
    if request.method == 'POST':
        if form.is_valid():  # True/False
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            photo = form.cleaned_data.get('photo')

            user = User.objects.create_user(email, email, password)
            member = Member.objects.create(user=user, photo=photo)

            messages.success(request, f'Hi {member.user.username}, Sign Up Success')
            url = reverse('members:sign-up')
            return redirect(url)

    context = {
        'form_signup': form,
    }
    return render(request, 'members/signup.html', context)


def sign_in_page(request):
    if request.user.is_authenticated:
        return redirect('articles:list')

    form = SignInForm(request.POST or None, use_required_attribute=False)

    if request.method == 'POST':
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            # login / authenticate
            user = authenticate(username=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'{user.username} is authenticated', extra_tags='is-success')
                return redirect('articles:list')

            messages.error(request, 'Mismatch email and password', extra_tags='is-danger')
            return redirect('members:sign-in')

    context = {
        'form': form
    }
    return render(request, 'members/signin.html', context)


def sign_out_page(request):
    logout(request)
    return redirect('members:sign-in')


@login_required(login_url='/')
def profile_page(request):
    context = {
        'member': request.user.member
    }
    return render(request, 'members/profile.html', context)


@login_required(login_url='/')
def deactivate_page(request):
    user = request.user
    user.delete()

    logout(request)

    return redirect('members:sign-up')

templates/members/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
    {% include 'navbar.html' %}

    <p>{{ member.user.email }}</p>
    <p>{{ member.created_at }}</p>
    <img src="{{ member.photo.url }}" alt="profile" width="120">
    <br>
    <a href="{% url 'members:deactivate' %}" class="button is-danger">Deactivate</a>

{% endblock %}

templates/members/signin.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Sign In{% endblock %}

{% block content %}

    <div class="columns">
        <div class="column">

            {% include 'navbar.html' %}

            <div class="container">

                <div class="columns">
                    <div class="column is-half">

                        {% if messages %}
                            {% for message in messages %}
                                <article class="message is-success">
                                    <div class="message-header">
                                        <p>Success</p>
                                        <button class="delete" aria-label="delete"></button>
                                    </div>
                                    <div class="message-body">{{ message }}</div>
                                </article>
                            {% endfor %}
                        {% endif %}

                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="field">
                                <div class="control">
                                    <label class="label">{{ form.email.label }}</label>
                                    {{ form.email|add_class:"input" }}
                                    <label class="label has-text-danger">{{ form.errors.email }}</label>
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                    <label class="label">{{ form.password.label }}</label>
                                    {{ form.password|add_class:"input" }}
                                    <label class="label has-text-danger">{{ form.errors.password }}</label>
                                </div>
                            </div>
                            <input type="submit" class="button"/>
                        </form>

                        <br/>
                        <p>Belum punya akun? <a href="{% url 'members:sign-up' %}">daftar disini</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/members/signup.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Sign Up CMSKU{% endblock %}

{% block content %}

    <div class="columns">
        <div class="column is-half">
            <p>Sign Up CMSKU</p>
            <hr/>

            {% if messages %}
                {% for message in messages %}
                    <article class="message {{ message.extra_tags }}">
                        <div class="message-header">
                            <p>Success {{ message.extra_tags }}</p>
                            <button class="delete" aria-label="delete"></button>
                        </div>
                        <div class="message-body">{{ message }}</div>
                    </article>
                {% endfor %}
            {% endif %}

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="field">
                    <div class="control">
                        <label class="label">{{ form_signup.email.label }}</label>
                        {{ form_signup.email|add_class:"input" }}
                        <label class="label has-text-danger">{{ form_signup.errors.email }}</label>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label">{{ form_signup.password.label }}</label>
                        {{ form_signup.password|add_class:"input" }}
                        <label class="label has-text-danger">{{ form_signup.errors.password }}</label>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label">{{ form_signup.photo.label }}</label>
                        {{ form_signup.photo|add_class:"input" }}
                        <label class="label has-text-danger">{{ form_signup.errors.photo }}</label>
                    </div>
                </div>
                <input type="submit" class="button"/>
            </form>
        </div>
    </div>

{% endblock content %}