articles/urls.py
from django.urls import path

from articles.views import (
    submit_article_page,
    list_article_page,
    delete_article_page,
    update_article_page,
    publish_article_page,
    LibraryPage, DetailArticlePage, submit_comment_page, statistic_page
)

app_name = 'articles'

urlpatterns = [
    path('submit/', submit_article_page, name='submit'),
    path('list/', list_article_page, name='list'),
    path('libraries/', LibraryPage.as_view(), name='library'),
    path('stats/', statistic_page, name='stats'),
    path('detail/<int:article_id>', DetailArticlePage.as_view(), name='detail'),
    path('delete/<int:article_id>', delete_article_page, name='delete'),
    path('update/<int:article_id>', update_article_page, name='update'),
    path('publish/<int:article_id>', publish_article_page, name='publish'),
    path('comment/<int:article_id>', submit_comment_page, name='comment')
]

cmsku/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls', namespace='members')),
    path('article/', include('articles.urls', namespace='articles'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

members/urls.py
from django.urls import path

from members.views import (
    sign_up_page,
    sign_in_page,
    sign_out_page,
    profile_page,
    deactivate_page,
)

app_name = 'members'

urlpatterns = [
    path('sign-out/', sign_out_page, name='sign-out'),
    path('sign-up/', sign_up_page, name='sign-up'),
    path('profile/', profile_page, name='profile'),
    path('deactivate/', deactivate_page, name='deactivate'),
    path('', sign_in_page, name='sign-in'),
]

articles/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

from helpers.models import BaseModel
from members.models import Member


class Category(BaseModel):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Article(BaseModel):
    title = models.CharField(max_length=120)
    content = models.TextField()
    slug = models.SlugField()
    published_at = models.DateTimeField(null=True, blank=True)
    is_published = models.BooleanField(default=False)

    author = models.ForeignKey(Member, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Auto generate slug ketika save ke database.
        self.slug = slugify(self.title)

        # Auto isi published_at saat save dengan kondisi is_published
        # bernilai True.
        if self.is_published:
            self.published_at = timezone.now()

        # Save perubahan ke database.
        super(Article, self).save(*args, **kwargs)


class Comment(BaseModel):
    content = models.TextField()

    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(Member, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.article.title}: {self.content}'

articles/forms.py
from django import forms

from articles.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'category']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

articles/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView

from articles.forms import ArticleForm, CommentForm
from articles.models import Article
from members.models import Member


@login_required(login_url='/')
def submit_article_page(request):
    form = ArticleForm(request.POST or None, use_required_attribute=False)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user.member
        article.save()

        return redirect('articles:list')

    context = {
        'form': form,
    }
    return render(request, 'articles/submit.html', context)


@login_required(login_url='/')
def list_article_page(request):
    articles = Article.objects.filter(author=request.user.member)
    context = {
        'articles': articles,
    }
    return render(request, 'articles/list.html', context)


@login_required(login_url='/')
def delete_article_page(request, article_id):
    article = Article.objects.get(id=article_id)
    article.delete()
    return redirect('articles:list')


@login_required(login_url='/')
def update_article_page(request, article_id):
    # manual handling invalid article
    # try:
    #     article = Article.objects.get(id=article_id)
    # except Article.DoesNotExist:
    #     return HttpResponse('data gak ketemu')

    # get article or throw 404 if invalid id.
    article = get_object_or_404(Article, id=article_id)

    form = ArticleForm(request.POST or None, use_required_attribute=False, instance=article)
    if form.is_valid():
        form.save()
        return redirect('articles:list')

    context = {
        'form': form,
    }
    return render(request, 'articles/submit.html', context)


@login_required(login_url='/')
def publish_article_page(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if article.is_published:
        article.is_published = False
        article.published_at = None
    else:
        article.is_published = True
    article.save()
    return redirect('articles:list')


@login_required(login_url='/')
def submit_comment_page(request, article_id):
    form = CommentForm(request.POST or None)
    url = reverse('articles:detail', args=[article_id])
    if request.method == 'POST':
        if form.is_valid():
            article = get_object_or_404(Article, id=article_id)

            comment = form.save(commit=False)
            comment.article = article
            comment.author = request.user.member
            comment.save()

            return redirect(url)
    return redirect(url)


def statistic_page(request):
    """
    tampilkan secara berurut:
    - article paling banyak di komentari [v]
    - member paling banyak menulis komentar [v]
    - member paling banyak menulis article [v]
    """
    most_writer = (Member.objects.filter(article__is_published=True)
                                 .annotate(total_article=Count('article'))
                                 .order_by('-total_article')[:3])
    most_commenter = (Member.objects.annotate(total_comment=Count('comment'))
                                    .order_by('-total_comment')[:3])
    most_commented_articles = (Article.objects.annotate(total_comment=Count('comment'))
                                              .order_by('-total_comment')[:3])
    total_article = Article.objects.filter(is_published=True).count()

    context = {
        'most_writer': most_writer,
        'most_commenter': most_commenter,
        'most_commented_articles': most_commented_articles,
        'total_article': total_article,
    }
    return render(request, 'articles/statistics.html', context)


class LibraryPage(ListView):
    model = Article
    template_name = 'articles/library.html'

    def get_queryset(self):
        return Article.objects.filter(is_published=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        kwargs['articles'] = self.get_queryset()
        return kwargs


class DetailArticlePage(DetailView):
    model = Article
    template_name = 'articles/detail.html'
    pk_url_kwarg = 'article_id'

    def get_context_data(self, **kwargs):
        kwargs['article'] = self.get_object()
        kwargs['comment_form'] = CommentForm()
        return kwargs

templates/articles/detail.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}CMSKU{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="columns">
        <div class="column">
            <div class="container">
                <strong>{{ article.title }}</strong>
                <p>published at {{ article.published_at }} by {{ article.author.user.username }}</p>
                <hr/>
                <p>{{ article.content }}</p>
            </div>
        </div>
    </div>
    <br>
    <hr>
    <div class="columns">
        <div class="column">
            <div class="container">
                {% for comment in article.comment_set.all %}
                    <p>{{ comment.content }} at {{ comment.created_at|date:"d M Y" }} by: {{ comment.author }}</p>
                {% endfor %}

            </div>
        </div>
    </div>
    <br>
    <hr>
    <div class="columns">
        <div class="column">
            <div class="container">
                {% if request.user.is_authenticated %}
                    <form action="{% url 'articles:comment' article.id %}" method="post">
                        {% csrf_token %}
                        <div class="field">
                            <div class="control">
                                {{ comment_form.content|add_class:"input" }}
                                <label class="label has-text-danger">{{ comment_form.errors.content }}</label>
                            </div>
                        </div>
                        <input type="submit" class="button" value="Submit a Comment">
                    </form>
                {% else %}
                    <strong>You need to login to comment this article. <a href="{% url 'members:sign-in' %}">Sign In</a></strong>
                {% endif %}
            </div>
        </div>
    </div>


{% endblock content %}

templates/articles/library.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}CMSKU{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        <div class="columns">
            {% for article in articles %}
                <div class="column">
                    <div class="card">
                        <div class="card-content">
                            <p class="title"><a href="{% url 'articles:detail' article.id %}">{{ article.title }}</a>
                            </p>
                            <p class="subtitle">by: {{ article.author.user.email }}</p>
                        </div>
                        <footer class="card-footer">
                            <p class="card-footer-item">
                                <span>{{ article.comment_set.all.count }} Comment</span>
                            </p>
                        </footer>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

templates/articles/list.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}List article | CMSKU{% endblock %}

{% block content %}
    {% include 'navbar.html' %}

    <div class="columns">
        <div class="column">
            <div class="container">
                <div class="notification">
                    Logged on as: <a href="{% url 'members:profile' %}" class="has-text-success"><strong>{{ request.user.email }}</strong></a>
                    |
                    <a href="{% url 'members:sign-out' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <div class="columns">
        <div class="column">
            <div class="container">
                <a href="{% url 'articles:submit' %}" class="button is-link">Add New Article</a>
            </div>
        </div>
    </div>

    <div class="columns">
        <div class="column">
            <div class="container">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Slug</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th>Publish Date</th>
                        <th>Total Comment</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for article in articles %}
                        <tr>
                            <td>{{ article.title }}</td>
                            <td>{{ article.slug }}</td>
                            <td>{{ article.category.name }}</td>
                            <td>{{ article.is_published|yesno:"Published,Draft" }}</td>
                            <td>{{ article.published_at|default_if_none:"-" }}</td>
                            <td>{{ article.comment_set.all.count }}</td>
                            <td>
                                <a href="{% url 'articles:delete' article.id %}" class="button is-danger">Delete</a>
                                <a href="{% url 'articles:update' article.id %}" class="button">Edit</a>
                                <a href="{% url 'articles:publish' article.id %}" class="button is-primary">
                                    {% if article.is_published %}Unpublish{% else %}Publish{% endif %}</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

templates/articles/public_list.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}List article | CMSKU{% endblock %}

{% block content %}

    <div class="columns">
        <div class="column">
            <div class="container">
                <div class="notification">
                    <strong>Logged on as: {{ request.user.email }}</strong> | <a href="{% url 'members:sign-out' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <div class="columns">
        <div class="column">
            <div class="container">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Slug</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th>Publish Date</th>
                        <th>Total Comment</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for article in articles %}
                        <tr>
                            <td>{{ article.title }}</td>
                            <td>{{ article.slug }}</td>
                            <td>{{ article.category.name }}</td>
                            <td>{{ article.is_published|yesno:"Published,Draft" }}</td>
                            <td>{{ article.published_at|default_if_none:"-" }}</td>
                            <td>{{ article.comment_set.all.count }}</td>
                            <td>
                                <a href="{% url 'articles:delete' article.id %}" class="button is-danger">Delete</a>
                                <a href="{% url 'articles:update' article.id %}" class="button">Edit</a>
                                <a href="{% url 'articles:publish' article.id %}" class="button is-primary">{% if article.is_published %}Unpublish{% else %}Publish{% endif %}</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

templates/articles/statistics.html
{% extends 'base.html' %}

{% block title %}Statistics{% endblock %}

{% block content %}
    {% include 'navbar.html' %}

    <div class="columns">
        <div class="column">
            <table class="table">
                <thead>
                    <tr>
                        <td colspan="2"><strong>Top Writer</strong></td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>Total Article</td>
                    </tr>
                </thead>
                <tbody>
                {% for author in most_writer %}
                    <tr>
                        <td>{{ author.user.email }}</td>
                        <td>{{ author.total_article }} out of {{ total_article }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <div class="column">
            <table class="table">
                <thead>
                <tr>
                    <td colspan="2"><strong>Top Commenter</strong></td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td>Total Comment</td>
                </tr>
                </thead>
                <tbody>
                {% for author in most_commenter %}
                    <tr>
                        <td>{{ author.user.email }}</td>
                        <td>{{ author.total_comment }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <div class="column">
            <table class="table">
                <thead>
                <tr>
                    <td colspan="2"><strong>Top Commented Article</strong></td>
                </tr>
                <tr>
                    <td>Title</td>
                    <td>Total Comment</td>
                </tr>
                </thead>
                <tbody>
                {% for article in most_commented_articles %}
                    <tr>
                        <td>{{ article.title }}</td>
                        <td>{{ article.total_comment }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/articles/submit.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Submit CMSKU{% endblock %}

{% block content %}

    <div class="columns">
        <div class="column is-half">
            <p>Submit Article CMSKU</p>
            <hr/>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="field">
                    <div class="control">
                        <label class="label">{{ form.title.label }}</label>
                        {{ form.title|add_class:"input" }}
                        <label class="label has-text-danger">{{ form.errors.title }}</label>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label">{{ form.content.label }}</label>
                        {{ form.content|add_class:"input" }}
                        <label class="label has-text-danger">{{ form.errors.content }}</label>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label">{{ form.category.label }}</label>
                        {{ form.category|add_class:"input" }}
                        <label class="label has-text-danger">{{ form.errors.category }}</label>
                    </div>
                </div>
                <input type="submit" class="button"/>
            </form>
        </div>
    </div>

{% endblock content %}