articles/urls.py
from django.urls import path

from articles.views import (
    submit_article_page,
    list_article_page,
    delete_article_page,
    update_article_page,
    publish_article_page,
    LibraryPage, DetailArticlePage, submit_comment_page, statistic_page
)

app_name = 'articles'

urlpatterns = [
    path('submit/', submit_article_page, name='submit'),
    path('list/', list_article_page, name='list'),
    path('libraries/', LibraryPage.as_view(), name='library'),
    path('stats/', statistic_page, name='stats'),
    path('detail/<int:article_id>', DetailArticlePage.as_view(), name='detail'),
    path('delete/<int:article_id>', delete_article_page, name='delete'),
    path('update/<int:article_id>', update_article_page, name='update'),
    path('publish/<int:article_id>', publish_article_page, name='publish'),
    path('comment/<int:article_id>', submit_comment_page, name='comment')
]

cmsku/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls', namespace='members')),
    path('article/', include('articles.urls', namespace='articles'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
{% block content %}{% endblock content %}
</body>
</html>

templates/navbar.html
<div class="notification">
    <div class="navbar-menu">
        <div class="navbar-start">
            <a href="{% url 'articles:library' %}" class="navbar-item">Explore Articles</a>
            <a href="{% url 'articles:stats' %}" class="navbar-item">Statistics</a>
        </div>
    </div>
</div>
<br/>